const appname = "UMarket";
const appversion = "Version: 1.0.0";
const credits = "@MrOrange";
const email = "Email";
const emailHint = "username@gmail.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "First Name";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const recoverPass = "Recover password";
const createNewAccount = "or, create a new account";
const loginWith = "Login in with";
const privacyPolicy = "Privacy Policy";
const errorProcesShopping = "You don't have product in cart";
const loggedin = "Logged in succsessfully";
const recoverPasswordStatus = "Recover link send from email";
const loggedout = "Logged out succsessfully";
const termAndCond = "Term and Conditions";
const alreadyHaveAccount = "Already have an account? ";
const typeRegistration = "Choose type Login and Singup";
const registrationByer = "Login like Byer";
const registrationSeller = "Login like Seller";
const questionTypeRegistration =
    "What type of account do you want to register?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchanything = "Search anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Woomen Dress",
    girlsWathces = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "TShirts",
    girlsDress = "Girls Dresses",
    featuredProduct = "Featured Product",
    featuredCategories = "Featured Categories";
// category strings
const womenClothing = "Women Clotching",
    menClotchingFashion = "Men Clotching & Fashion",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    kidtoys = "Kids & Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    telephone = "Cellphone & Tab",
    furniture = "Furniture";
// item details strings
const video = "Video",
    reviews = "Reviews",
    sellerpolicy = "Seller Policy",
    returnpolity = "Return Policy",
    supportpolity = "Support Policy",
    productsyoumaylike = "Products you may also like";
// name button
const logout = "Logout";
// profile strings
const wishlist = "My Wishlist",
    orders = "My Orders",
    message = "Messages",
    oldpass = "Old password",
    newpass = "New Password";
// payment method strings
const googlePay = "Google Pay",
    applePay = "Apple Pay",
    stripe = "Stripe",
    cod = "Cash on delivery";
// seller app strings
const welcome = "Hi, Welcome to",
    forgotPassword = "Forgot Password?",
    anyProblem = "In case of any difficulty, contact administration",
    dashboard = "Dashboard",
    rating = "Rating",
    unpaid = "Unpaid",
    shopSettings = "Shop Settings",
    messages = "Messages",
    totalSales = "Total Profit",
    popular = "Popular Products",
    loginTo = "Login to your account",
    products = "Products",
    settings = "Settings",
    featured = "Featured",
    editProfile = "Edit Profile",
    changeImage = "Change Image",
    save = "Save",
    remove = "Remove",
    chats = "Chats",
    confirmPass = "Confirm Password",
    credit = "@MrOrange";
// shop settings strings
const shopDescHint = "Enter you shop description",
    shopWebsiteHint = "eg. vendor.umart.com",
    shopMobileHint = "eg. +92123456789",
    shopAddressHint = "eg. Near Railway Bazaar",
    description = "Description",
    mobile = "Shop Mobile",
    website = "Shop Website",
    shopName = "Shop Name",
    address = "Shop Address";
